# Generated by Django 4.1.7 on 2023-03-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, unique=True)),
                ('born_date', models.CharField(max_length=30)),
                ('born_location', models.CharField(max_length=150)),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=100)),
                ('quote', models.TextField(unique=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_mysite.author')),
            ],
        ),
    ]
