# Generated by Django 4.1.7 on 2023-03-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mysite', '0010_alter_quote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(),
        ),
    ]
