# Generated by Django 4.1.7 on 2023-03-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mysite', '0017_alter_quote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(max_length=2700, unique=True),
        ),
    ]
