# Generated by Django 4.1.7 on 2023-03-26 22:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mysite', '0019_alter_author_born_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=200), blank=True, size=None),
        ),
    ]
