# Generated by Django 4.1.7 on 2023-03-26 23:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mysite', '0020_alter_quote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), blank=True, size=None),
        ),
    ]
