# Generated by Django 4.1.7 on 2023-03-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mysite', '0037_alter_author_id_alter_quote_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='author',
            new_name='author_id',
        ),
    ]
