# Generated by Django 4.1.7 on 2023-03-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mysite', '0039_rename_author_id_quote_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
