# Generated by Django 4.1.7 on 2023-03-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mysite', '0041_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='author',
            new_name='author_id',
        ),
    ]
