# Generated by Django 4.1.7 on 2023-03-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mysite', '0046_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
