# Generated by Django 4.1.7 on 2023-03-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mysite', '0055_alter_author_id_alter_author_user_alter_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
