# Generated by Django 4.1.7 on 2023-03-28 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mysite', '0058_alter_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_mysite.author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
